#ifndef MHADVANCEDAUDIO_HPP
#define MHADVANCEDAUDIO_HPP
#include <Util/MhGlobals.hpp>
#if defined(MH_UTIL_EXPORT)
#define MH_ADV_AUDIO_API MH33_API_EXPORT
#else
#define MH_ADV_AUDIO_API MH33_API_IMPORT
#endif
#endif // MHADVANCEDAUDIO_HPP
